/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'carlos' at '10/19/16 5:29 PM' with Gradle 3.1
 *
 * @author carlos, @date 10/19/16 5:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
